packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - dugite
  - esbuild
  - lefthook
  - lightningcss

allowBuilds:
  dugite: true
  esbuild: true
  lefthook: true
  lightningcss: true
  unrs-resolver: true
  msw: false
