/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WikiRouteImport } from "./routes/wiki"
import { Route as WikiIndexRouteImport } from "./routes/wiki.index"
import { Route as WikiWikiIdRouteImport } from "./routes/wiki.$wikiId"
import { Route as WikiWikiIdIndexRouteImport } from "./routes/wiki.$wikiId.index"
import { Route as WikiWikiIdSplatRouteImport } from "./routes/wiki.$wikiId.$"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: "/wiki",
  path: "/wiki",
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WikiRoute,
} as any)
const WikiWikiIdRoute = WikiWikiIdRouteImport.update({
  id: "/$wikiId",
  path: "/$wikiId",
  getParentRoute: () => WikiRoute,
} as any)
const WikiWikiIdIndexRoute = WikiWikiIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WikiWikiIdRoute,
} as any)
const WikiWikiIdSplatRoute = WikiWikiIdSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => WikiWikiIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/wiki": typeof WikiRouteWithChildren
  "/wiki/$wikiId": typeof WikiWikiIdRouteWithChildren
  "/wiki/": typeof WikiIndexRoute
  "/wiki/$wikiId/$": typeof WikiWikiIdSplatRoute
  "/wiki/$wikiId/": typeof WikiWikiIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/wiki": typeof WikiIndexRoute
  "/wiki/$wikiId/$": typeof WikiWikiIdSplatRoute
  "/wiki/$wikiId": typeof WikiWikiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/wiki": typeof WikiRouteWithChildren
  "/wiki/$wikiId": typeof WikiWikiIdRouteWithChildren
  "/wiki/": typeof WikiIndexRoute
  "/wiki/$wikiId/$": typeof WikiWikiIdSplatRoute
  "/wiki/$wikiId/": typeof WikiWikiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/wiki"
    | "/wiki/$wikiId"
    | "/wiki/"
    | "/wiki/$wikiId/$"
    | "/wiki/$wikiId/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/wiki" | "/wiki/$wikiId/$" | "/wiki/$wikiId"
  id:
    | "__root__"
    | "/"
    | "/wiki"
    | "/wiki/$wikiId"
    | "/wiki/"
    | "/wiki/$wikiId/$"
    | "/wiki/$wikiId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WikiRoute: typeof WikiRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/wiki": {
      id: "/wiki"
      path: "/wiki"
      fullPath: "/wiki"
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/wiki/": {
      id: "/wiki/"
      path: "/"
      fullPath: "/wiki/"
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    "/wiki/$wikiId": {
      id: "/wiki/$wikiId"
      path: "/$wikiId"
      fullPath: "/wiki/$wikiId"
      preLoaderRoute: typeof WikiWikiIdRouteImport
      parentRoute: typeof WikiRoute
    }
    "/wiki/$wikiId/": {
      id: "/wiki/$wikiId/"
      path: "/"
      fullPath: "/wiki/$wikiId/"
      preLoaderRoute: typeof WikiWikiIdIndexRouteImport
      parentRoute: typeof WikiWikiIdRoute
    }
    "/wiki/$wikiId/$": {
      id: "/wiki/$wikiId/$"
      path: "/$"
      fullPath: "/wiki/$wikiId/$"
      preLoaderRoute: typeof WikiWikiIdSplatRouteImport
      parentRoute: typeof WikiWikiIdRoute
    }
  }
}

interface WikiWikiIdRouteChildren {
  WikiWikiIdSplatRoute: typeof WikiWikiIdSplatRoute
  WikiWikiIdIndexRoute: typeof WikiWikiIdIndexRoute
}

const WikiWikiIdRouteChildren: WikiWikiIdRouteChildren = {
  WikiWikiIdSplatRoute: WikiWikiIdSplatRoute,
  WikiWikiIdIndexRoute: WikiWikiIdIndexRoute,
}

const WikiWikiIdRouteWithChildren = WikiWikiIdRoute._addFileChildren(
  WikiWikiIdRouteChildren
)

interface WikiRouteChildren {
  WikiWikiIdRoute: typeof WikiWikiIdRouteWithChildren
  WikiIndexRoute: typeof WikiIndexRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiWikiIdRoute: WikiWikiIdRouteWithChildren,
  WikiIndexRoute: WikiIndexRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
