export const amendChannels = Object.freeze({
  chooseWorkspaceLocation: "amend:workspaces:choose-location",
  createWorkspace: "amend:workspaces:create",
  openWorkspace: "amend:workspaces:open",
  getCurrentWorkspace: "amend:workspaces:current",
  listWorkspaces: "amend:workspaces:list",
  activateWorkspace: "amend:workspaces:activate",
  getProviderStatus: "amend:providers:status",
  listProviders: "amend:providers:list",
  listProviderModels: "amend:providers:list-models",
  startProviderOAuth: "amend:providers:start-oauth",
  respondToProviderOAuthPrompt: "amend:providers:respond-to-oauth-prompt",
  cancelProviderOAuth: "amend:providers:cancel-oauth",
  connectProviderWithApiKey: "amend:providers:connect-with-api-key",
  setDefaultProviderModel: "amend:providers:set-default-model",
  providerOAuthEvent: "amend:providers:oauth-event",
  chooseSourceDocument: "amend:wiki:choose-document",
  registerSourceDocument: "amend:wiki:register-document",
  startIngest: "amend:wiki:start-ingest",
  getCurrentIngest: "amend:wiki:current-ingest",
  cancelIngest: "amend:wiki:cancel-ingest",
  refreshWikiIndex: "amend:wiki:refresh-index",
  listWikiFiles: "amend:wiki:list-files",
  readWikiFile: "amend:wiki:read-file",
  searchWiki: "amend:wiki:search",
  listWikiTags: "amend:wiki:list-tags",
  ingestChanged: "amend:wiki:ingest-changed",
})
