export const amendChannels = Object.freeze({
  chooseWorkspaceParent: "amend:workspace:choose-parent",
  createWorkspace: "amend:workspace:create",
  getCurrentWorkspace: "amend:workspace:current",
  piStatus: "amend:pi:status",
  listPiApiKeyProviders: "amend:pi:list-api-key-providers",
  listPiModels: "amend:pi:list-models",
  startPiOAuthLogin: "amend:pi:start-oauth-login",
  respondToPiPrompt: "amend:pi:respond-to-prompt",
  cancelPiLogin: "amend:pi:cancel-login",
  savePiApiKeyCredential: "amend:pi:save-api-key-credential",
  setPiDefaultModel: "amend:pi:set-default-model",
  piLoginEvent: "amend:pi:login-event",
  chooseSourceDocument: "amend:wiki:choose-document",
  registerSourceDocument: "amend:wiki:register-document",
  startIngest: "amend:wiki:start-ingest",
  getCurrentIngest: "amend:wiki:current-ingest",
  cancelIngest: "amend:wiki:cancel-ingest",
  refreshWikiIndex: "amend:wiki:refresh-index",
  searchWiki: "amend:wiki:search",
  listWikiTags: "amend:wiki:list-tags",
  ingestChanged: "amend:wiki:ingest-changed",
})
